/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * miAbrirRemMissing.java
 *
 * Created on 25-may-2012, 14:33:43
 */
package gui.Icons.Filters.ReplaceMissing;

import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Juan Carlos
 */
public class miAbrirRemMissing extends javax.swing.JFrame {
    
    AbstractTableModel datosEntrada;
    String atributos[];
    Object remcon;
    int colsel;
    
    //ggg
    public miAbrirRemMissing() {
        initComponents();
    }

    /** Creates new form miAbrirRemMissing */
    public miAbrirRemMissing(AbstractTableModel datosEntrada) {
        this.datosEntrada = datosEntrada;
        atributos = new String[datosEntrada.getColumnCount()+1];
        atributos[0] = "Select an Attribute";
        for(int i = 0; i < datosEntrada.getColumnCount(); i++) {
            atributos[i+1] = datosEntrada.getColumnName(i);
        }
        initComponents();
    }
    
    public void setDatas(AbstractTableModel di, int indexColumn, Object replaceWith) {
        this.datosEntrada = di;
        
        if(atributos == null){
            atributos = new String[datosEntrada.getColumnCount()+1];
            atributos[0] = "Select an Attribute";
            CmbAtributos.addItem(atributos[0]);
            for(int i = 0; i < datosEntrada.getColumnCount(); i++) {
                atributos[i+1] = datosEntrada.getColumnName(i);
                CmbAtributos.addItem(datosEntrada.getColumnName(i));
            }
        }
        
        CmbAtributos.setSelectedIndex(indexColumn);
        
        TxtRemCon.setText(replaceWith.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAplicar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtRemCon = new javax.swing.JTextField();
        CmbAtributos = new javax.swing.JComboBox();
        BtnReset = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnAplicar.setForeground(new java.awt.Color(51, 51, 51));
        BtnAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        BtnAplicar.setText("Play");
        BtnAplicar.setToolTipText("Execute the Configuration");
        BtnAplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAplicar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAplicarMouseClicked(evt);
            }
        });
        BtnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAplicarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Value by replacing");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Attribute");

        TxtRemCon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtRemCon.setToolTipText("Value to replace");

        CmbAtributos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CmbAtributos.setToolTipText("Select an Attribute");

        BtnReset.setForeground(new java.awt.Color(51, 51, 51));
        BtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo.png"))); // NOI18N
        BtnReset.setText("Reset");
        BtnReset.setToolTipText("Resete the Parameters");
        BtnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnCerrar.setForeground(new java.awt.Color(51, 51, 51));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        BtnCerrar.setText("Close");
        BtnCerrar.setToolTipText("Close the Configuration");
        BtnCerrar.setEnabled(false);
        BtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35))
                    .addComponent(TxtRemCon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(CmbAtributos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnReset, 0, 0, Short.MAX_VALUE)
                    .addComponent(BtnAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnAplicar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCerrar)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnReset)
                    .addComponent(TxtRemCon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAplicarMouseClicked
        
}//GEN-LAST:event_BtnAplicarMouseClicked

    private void BtnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAplicarActionPerformed
        String cad,valmen;
        char uc;
        int bdcadint=0, bdcolint=0,x=0;
        //------------------------
        colsel = datosEntrada.findColumn(CmbAtributos.getModel().getSelectedItem().toString());
        if(colsel == -1){
            TxtRemCon.setText("");
            JOptionPane.showMessageDialog(this, "You must select some Attribute","Error in Configure Remplace Missing",JOptionPane.ERROR_MESSAGE);
        }else if(TxtRemCon.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty text: Value by replacing","Error in Configure Remplace Missing",JOptionPane.ERROR_MESSAGE);
        }else {
            
            if(esEntero(TxtRemCon.getText())){
               remcon = Integer.parseInt(TxtRemCon.getText());
            }else if(esDouble(TxtRemCon.getText())){
               remcon = Double.parseDouble(TxtRemCon.getText());
            }else {
               remcon = TxtRemCon.getText();
            }
            BtnCerrar.setEnabled(true);
            
//            if(datosEntrada.getColumnClass(colsel).getSimpleName().equals("String")) {  //************
//              remcon = TxtRemCon.getText();
//              BtnCerrar.setEnabled(true);
//            }else if(datosEntrada.getColumnClass(colsel).getSimpleName().equals("Integer") && esEntero(TxtRemCon.getText())) {  //************
//              remcon = Integer.parseInt(TxtRemCon.getText());
//              BtnCerrar.setEnabled(true);
//            }else if(datosEntrada.getColumnClass(colsel).getSimpleName().equals("Double") && esDouble(TxtRemCon.getText())) {  //************
//              remcon = Double.parseDouble(TxtRemCon.getText());
//              BtnCerrar.setEnabled(true);
//            }else {
//                TxtRemCon.setText("");
//                JOptionPane.showMessageDialog(this, "The data types are different ","Error in Configure Remplace Missing.",JOptionPane.ERROR_MESSAGE);
//            }
          
            
//            if(datosEntrada.getColumnClass(colsel).getSimpleName().equals("Integer")) {  //************
//                bdcolint = 1;
//                
//            }else if(datosEntrada.getColumnClass(colsel).getSimpleName().equals("Short")) {  //************
//                bdcolint = 1;        //Considerar una para los Short
//            } else  bdcolint = 0;
//            
//            cad = TxtRemCon.getText();
//            for(int y = 0; y < cad.length(); y++) {
//                uc = cad.charAt(y);
//                if(uc>47 && uc<58) x++;
//            }
//            if(x==cad.length()) bdcadint = 1;
//            else bdcadint = 0;
//            
//            if(bdcadint==bdcolint && bdcadint==1) {
//                remcon = Integer.parseInt(TxtRemCon.getText());
//                BtnCerrar.setEnabled(true);
//            } else if(bdcadint==bdcolint && bdcadint==0) {
//                remcon = TxtRemCon.getText();
//                BtnCerrar.setEnabled(true);
//            } else {
//                TxtRemCon.setText("");
//                JOptionPane.showMessageDialog(this, "The data types are different ","Error in Configure Remplace Missing.",JOptionPane.ERROR_MESSAGE);
//            }
        }
}//GEN-LAST:event_BtnAplicarActionPerformed

    public boolean esEntero(String cad){
        boolean bd = false;
        int valNum = 0;
                
        try{  // si lo puede transformar a numero lo transforma a numero
          valNum = Integer.parseInt(cad);
          bd = true;
        } catch (Exception e) {
          bd = false;
        }
        return bd;
    }

    public boolean esDouble(String cad){
        boolean bd = false;
        double valNum = 1.0;
                
        try{  // si lo puede transformar a numero lo transforma a numero
          valNum = Double.parseDouble(cad);
          bd = true;
        } catch (Exception e) {
          bd = false;
        }
        return bd;
    }
     
    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
        
}//GEN-LAST:event_BtnResetMouseClicked

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        CmbAtributos.setModel(new javax.swing.DefaultComboBoxModel(atributos));
        TxtRemCon.setText("");
}//GEN-LAST:event_BtnResetActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        //System.exit( 0 );
        this.dispose();
}//GEN-LAST:event_BtnCerrarActionPerformed

    public int getColSelec() {
        return colsel;
    }
    
    public Object getValRem() {
        return remcon;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new miAbrirRemMissing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAplicar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnReset;
    private javax.swing.JComboBox CmbAtributos;
    private javax.swing.JTextField TxtRemCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
