/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * miVerBirch.java
 *
 * Created on 23-jun-2012, 17:11:49
 */
package gui.Icons.Cluster.viewsClus;

import algorithm.cluster.jerarquico.Nodo;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.table.AbstractTableModel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author juank
 */
public class miVerBirch extends javax.swing.JFrame {

   JScrollPane scroll;
   BufferedImage image;
   pnlArbol miPanel;
   private Nodo raiz;    
   private DefaultMutableTreeNode raizTree;
   JTree arbol;
   
    public miVerBirch() {
        initComponents();
    }
    
    public void ejecutar(Nodo _ra){
      this.raiz=_ra;
      scroll = new JScrollPane(); 
      miPanel=new pnlArbol();
      miPanel.dibujar(raiz);
      image = miPanel.crearPNG(890,690);
        
      raizTree = new DefaultMutableTreeNode("Root node");
      mostrarInorden(raiz,true,raizTree);
      arbol=new JTree(raizTree);     
      treeBirch.setModel(arbol.getModel());
    }
    
    public void mostrarInorden(Nodo r,boolean NodoRaiz,DefaultMutableTreeNode  rt){
          Nodo actu=null;
          DefaultMutableTreeNode  raizActu=null;
          DefaultMutableTreeNode  nodoNuevo=null;
          DefaultMutableTreeNode  datoNodo=null;

          if (NodoRaiz){
              actu = raiz;
              raizActu=raizTree;
          }
          else{
              actu = r;
              raizActu = rt;
          }
         
          
          if(actu != null){
             
                System.out.println("Level "+actu.nivel);
                String dat=" ";
                
                nodoNuevo = new DefaultMutableTreeNode("Level "+actu.nivel);
                
                for (int i=0;i<actu.dataNodo.getRowCount();i++){
                    dat="";
                    
                    for (int j=0;j<actu.dataNodo.getColumnCount();j++){
                        dat=dat + actu.dataOri.getValueAt(i,j).toString()+ "    ";
                    } 
                    
                    datoNodo =new DefaultMutableTreeNode(dat);
                    raizActu.add(datoNodo);
               } 
                
               raizActu.add(nodoNuevo);

               raizActu=nodoNuevo;
               mostrar(actu.dataNodo);
               mostrarInorden(actu.izquierda,false,raizActu);
               mostrarInorden(actu.derecha,false,raizActu);
          }
    }
 
 public void mostrar(AbstractTableModel tabla){
            System.out.println("Showing data ------ Jtree");
        for (int i=0;i<tabla.getRowCount();i++){
            for (int j=0;j<tabla.getColumnCount();j++){
                System.out.print("   "+tabla.getValueAt(i,j));
            }
             System.out.println("");
        }
    }
 public String getData(AbstractTableModel tabla){
        String strdatos="(";
        
        for (int i=0;i<tabla.getRowCount();i++){
            for (int j=0;j<tabla.getColumnCount();j++){
              strdatos=strdatos + tabla.getValueAt(i,j)+",";
            }
             strdatos=strdatos+") (";
        }
            return strdatos;
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        treeBirch = new javax.swing.JTree();
        bteEspand = new javax.swing.JButton();
        btnCollapse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setViewportView(treeBirch);

        bteEspand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16x16/mas.png"))); // NOI18N
        bteEspand.setText("Expand all");
        bteEspand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteEspandActionPerformed(evt);
            }
        });

        btnCollapse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16x16/menos.png"))); // NOI18N
        btnCollapse.setText("Collapse all");
        btnCollapse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollapseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bteEspand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCollapse))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bteEspand)
                    .addComponent(btnCollapse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bteEspandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteEspandActionPerformed
        int row = 0;
        while(row < treeBirch.getRowCount()) {
            treeBirch.expandRow(row);
            row++;
        }
    }//GEN-LAST:event_bteEspandActionPerformed

    private void btnCollapseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollapseActionPerformed
        int row = treeBirch.getRowCount();
        while(row > 0) {
            treeBirch.collapseRow(row);
            row--;
        }
    }//GEN-LAST:event_btnCollapseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new miVerBirch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bteEspand;
    private javax.swing.JButton btnCollapse;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree treeBirch;
    // End of variables declaration//GEN-END:variables
}
