/*
 * frmCredits.java
 *
 * Created on 12 de octubre de 2006, 20:58
 */

package Utils;

import java.util.Locale;
import javax.swing.JEditorPane;

/**
 *
 * @author  and
 */
public class Help extends javax.swing.JFrame {
    private String iconName;
    
    /** Creates new form frmCredits */
    public Help(String iconName) {
        this.iconName = iconName;
        initComponents();
        try {
            pnlHelp.setPage(getClass().getResource("/resource/" + iconName + "_en.html"));
        } catch (Exception e) {
            System.err.println("Failed to open " + iconName + "_en.html file");
        }
        pnlHelp.setEditable(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        groupTranslate = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlHelp = new JEditorPane("text/html", "<html>Help form</html>");
        btnEs = new javax.swing.JToggleButton();
        btnEn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png")));
        jButton1.setMnemonic('c');
        jButton1.setText("Close Help...");
        jButton1.setToolTipText("Return Aplication");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setToolTipText("Help Conetion BD");
        jScrollPane2.setViewportView(pnlHelp);

        btnEs.setBackground(new java.awt.Color(255, 255, 255));
        groupTranslate.add(btnEs);
        btnEs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CO")));
        btnEs.setText("Espa\u00f1ol");
        btnEs.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsActionPerformed(evt);
            }
        });

        btnEn.setBackground(new java.awt.Color(255, 255, 255));
        groupTranslate.add(btnEn);
        btnEn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EN")));
        btnEn.setSelected(true);
        btnEn.setText("English");
        btnEn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(btnEs)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnEn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 188, Short.MAX_VALUE)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {btnEn, btnEs}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(btnEs)
                        .add(btnEn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {btnEn, btnEs}, org.jdesktop.layout.GroupLayout.VERTICAL);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-770)/2, (screenSize.height-496)/2, 770, 496);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsActionPerformed
        try {
            pnlHelp.setPage(getClass().getResource("/resource/" + iconName + "_es.html"));
        } catch (Exception e) {
            System.err.println("Failed to open " + iconName + "_es.html file");
        }
    }//GEN-LAST:event_btnEsActionPerformed
    
    private void btnEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnActionPerformed
        try {
            pnlHelp.setPage(getClass().getResource("/resource/" + iconName + "_en.html"));
        } catch (Exception e) {
            System.err.println("Failed to open " + iconName + "_en.html file");
        }
    }//GEN-LAST:event_btnEnActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help("Connection DB").setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEn;
    private javax.swing.JToggleButton btnEs;
    private javax.swing.ButtonGroup groupTranslate;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane pnlHelp;
    // End of variables declaration//GEN-END:variables
}
