/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * miConnectionWizard.java
 *
 * Created on 25-may-2012, 15:04:45
 */
package gui.Icons.DBConnection;

import gui.KnowledgeFlow.ChooserEscritorio;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.SpinnerNumberModel;


/**
 *
 * @author Juan Carlos
 */
public class miConnectionWizard extends javax.swing.JFrame {
    
    private boolean CONEXION_EXITOSA = false;
    private Connection connection = null;
    private String DriverName;
    private String DBChar;
    private int x = 150, y = 25;
    public miSelectorTable selector;
    private DBConnectionIcon myDBConnectionIcon = null;

    /** Creates new form frmAsistente */
    public miConnectionWizard() {
        initComponents();
        DriverName = "jdbc:postgresql://";
        txtPuerto.setText("5432");
        DBChar = "/";
        selector = null;
    }
    
    public miConnectionWizard(DBConnectionIcon dbci) {
        initComponents();
        myDBConnectionIcon = dbci;
        DriverName = "jdbc:postgresql://";
        txtPuerto.setText("5432");
        DBChar = "/";
        selector = null;
    }
    
    public void updateIcon(DBConnectionIcon dbci) {
        myDBConnectionIcon = dbci;
        DriverName = "jdbc:postgresql://";
        txtPuerto.setText("5432");
        DBChar = "/";
        selector = null;
    }
    
    public void setVals(){
       cbxDriver.setSelectedIndex(myDBConnectionIcon.driver); 
       txtPuerto.setText(myDBConnectionIcon.port);
       txtHost.setText(myDBConnectionIcon.host);
       txtUsuario.setText(myDBConnectionIcon.user);
       txtPassword.setText(myDBConnectionIcon.password);
       txtBD.setText(myDBConnectionIcon.database);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDriver = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblBD = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        lblPuerto = new javax.swing.JLabel();
        cbxDriver = new javax.swing.JComboBox();
        txtUsuario = new javax.swing.JTextField();
        txtBD = new javax.swing.JTextField();
        txtHost = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtPuerto = new javax.swing.JTextField();
        btnAccept = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblStatusBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblDriver.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblDriver.setText("Driver JDBC:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblUsuario.setText("User:");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblPassword.setText("Password:");

        lblBD.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblBD.setText("DataBase:");

        lblHost.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblHost.setText("Host:");

        lblPuerto.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblPuerto.setText("Port:");

        cbxDriver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "org.postgresql.Driver", "com.mysql.jdbc.Driver", "oracle.jdbc.driver.OracleDriver" }));
        cbxDriver.setToolTipText("Driver JDBC name");
        cbxDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDriverActionPerformed(evt);
            }
        });

        txtUsuario.setToolTipText("User name");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        txtBD.setToolTipText("Database name");
        txtBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBDActionPerformed(evt);
            }
        });
        txtBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBDKeyTyped(evt);
            }
        });

        txtHost.setToolTipText("Host of the data base");
        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });

        btnConectar.setForeground(new java.awt.Color(51, 51, 51));
        btnConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connect_no.png"))); // NOI18N
        btnConectar.setText("Connect");
        btnConectar.setToolTipText("Connect...");
        btnConectar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConectar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        txtPassword.setToolTipText("Password user");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnAccept.setForeground(new java.awt.Color(51, 51, 51));
        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        btnAccept.setText("Play");
        btnAccept.setToolTipText("Accept the connection...");
        btnAccept.setEnabled(false);
        btnAccept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccept.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        btnexit.setText("Exit");
        btnexit.setEnabled(false);
        btnexit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnexit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jButton1.setText("JDBC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDriver)
                                .addGap(37, 37, 37)
                                .addComponent(jButton1))
                            .addComponent(lblPassword)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPuerto)
                                        .addGap(165, 165, 165))
                                    .addComponent(txtBD, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(txtPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(txtHost, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(cbxDriver, javax.swing.GroupLayout.Alignment.TRAILING, 0, 192, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblUsuario)
                                        .addGap(164, 164, 164))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblBD)
                                        .addGap(138, 138, 138)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnexit, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(btnConectar))))
                        .addContainerGap())
                    .addComponent(lblHost)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDriver))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPuerto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHost))
                    .addComponent(btnConectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAccept)
                        .addGap(82, 82, 82)
                        .addComponent(btnexit)))
                .addContainerGap())
        );

        lblStatusBar.setBackground(new java.awt.Color(255, 255, 255));
        lblStatusBar.setFont(new java.awt.Font("Dialog", 0, 10));
        lblStatusBar.setText("Wait Connection...");
        lblStatusBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblStatusBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDriverActionPerformed
        // TODO add your handling code here:
        switch(cbxDriver.getSelectedIndex()){
            case 0:
                DriverName = "jdbc:postgresql://";
                txtPuerto.setText("5432");
                DBChar = "/";
                break;
            case 1:
                DriverName = "jdbc:mysql://";
                txtPuerto.setText("3306");
                DBChar = "/";
                break;
            case 2:
                DriverName = "jdbc:oracle:thin:@";
                txtPuerto.setText("1521");
                DBChar = ":";
                break;
        }
    }//GEN-LAST:event_cbxDriverActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        btnAccept.setEnabled(false);
}//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtBDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBDKeyTyped
        btnAccept.setEnabled(false);
}//GEN-LAST:event_txtBDKeyTyped

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        String url = new String();
        try{
            Class.forName(cbxDriver.getSelectedItem().toString());
            url = DriverName + txtHost.getText() + ":" + txtPuerto.getText() + DBChar + txtBD.getText();
            //jdbc:oracle:thin:@190.124.10.4:1521:investigacion
            connection = DriverManager.getConnection(url, txtUsuario.getText(),new String(txtPassword.getPassword()));
            CONEXION_EXITOSA = true;
            // Conexion exitosa...
            //lblStatusBar.setIcon(new ImageIcon(getClass().getResource("/images/conectado")));
            lblStatusBar.setText("Success Connection to " + txtBD.getText() + " in " + txtHost.getText());
            ChooserEscritorio.setStatus("Success Connection to " + txtBD.getText() + " in " + txtHost.getText());
            btnAccept.setEnabled(true);
        } catch(SQLException e1){
            lblStatusBar.setText("SQLException: " + e1);
            ChooserEscritorio.setStatus("SQLException: " + e1);
        } catch(ClassNotFoundException e){
            lblStatusBar.setText("Error driver: " + e);
            ChooserEscritorio.setStatus("No load the driver: " + e);
        }
}//GEN-LAST:event_btnConectarActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        if(CONEXION_EXITOSA){
            myDBConnectionIcon.connection = this.connection;
            myDBConnectionIcon.info = lblStatusBar.getText();
            myDBConnectionIcon.getMnuSelector().setEnabled(true);
            myDBConnectionIcon.getMnuLoad().setEnabled(false);
            
            myDBConnectionIcon.driver = cbxDriver.getSelectedIndex();
            myDBConnectionIcon.port = txtPuerto.getText();
            myDBConnectionIcon.host = txtHost.getText();
            myDBConnectionIcon.user = txtUsuario.getText();
            myDBConnectionIcon.password = txtPassword.getText();
            myDBConnectionIcon.database= txtBD.getText();
        }
        btnexit.setEnabled(true);
}//GEN-LAST:event_btnAcceptActionPerformed
    
    
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBDActionPerformed

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHostActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.dispose();
}//GEN-LAST:event_btnexitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // esto sirve para copiar el driver jdbc en la caprpeta del jre/lib/ext
        
        //        para averiguar donde esta instalado el java
        String javaHome = System.getProperty("java.home");
        
        javaHome = javaHome.replace("\\","/");
                
        String javaPath = javaHome.concat("/lib/ext/mysql-connector-java-5.1.13-bin.jar");
        
        try {
                File inFile = new File("./mysql-connector-java-5.1.13-bin.jar");
                File outFile = new File(javaPath);
                
                if(!outFile.exists()) {
            
                    FileInputStream in = new FileInputStream(inFile);
                    FileOutputStream out = new FileOutputStream(outFile);

                    int c;
                    while( (c = in.read() ) != -1)
                            out.write(c);

                    in.close();
                    out.close();

                    lblStatusBar.setText(javaPath);
                }
                
        } catch(IOException e) {
                System.err.println(e);
	}  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new miConnectionWizard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnexit;
    private javax.swing.JComboBox cbxDriver;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBD;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblStatusBar;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtBD;
    private javax.swing.JTextField txtHost;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
