/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * miAbrirDiscretizacion.java
 *
 * Created on 25-may-2012, 11:37:27
 */
package gui.Icons.Filters.Discretize;

import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Juan Carlos
 */
public class miAbrirDiscretizacion extends javax.swing.JFrame {
    
    AbstractTableModel datosEntrada;
    String atributos[];
    int colsel, val, bdrbtn;

    /** Creates new form miAbrirDiscretizacion */
    public miAbrirDiscretizacion(AbstractTableModel dataIn) {
//        datosEntrada = dataIn;
//        atributos = new String[datosEntrada.getColumnCount()+1];
//        pa = 1;
//        atributos[0] = "Select an attribute";
//        for(int i = 0; i < datosEntrada.getColumnCount(); i++) {
//          if(datosEntrada.getColumnClass(i).getSimpleName().equals("Integer")) {
//             atributos[pa] = datosEntrada.getColumnName(i);
//             pa ++;
//          } 
//        }
//        initComponents();
    }
    
    public miAbrirDiscretizacion() {
        initComponents();
    }
    
    public void setDatas(AbstractTableModel dataIn, int columnSelected, int rangeValue, int optionRange) {
        datosEntrada = dataIn;
        if(atributos == null){
            atributos = new String[datosEntrada.getColumnCount()+1];
            atributos[0] = "Select an attribute";
            CmbAtributos.addItem(atributos[0]);
            for(int i = 1; i < datosEntrada.getColumnCount()+1; i++) {
              if(datosEntrada.getColumnClass(i-1).getSimpleName().equals("Integer")|| datosEntrada.getColumnClass(i-1).getSimpleName().equals("Double")) {
                 atributos[i] = datosEntrada.getColumnName(i-1);
                 CmbAtributos.addItem(atributos[i]);
              } 
            }
        }
        
        CmbAtributos.setSelectedIndex(columnSelected);
        
        if(optionRange==0){
           RbtnNR.setSelected(true);
           TexNR.setText(String.valueOf(rangeValue)); 
        }else if (optionRange==1){
           RbtnTR.setSelected(true);
           TexTR.setText(String.valueOf(rangeValue)); 
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BtnAplicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CmbAtributos = new javax.swing.JComboBox();
        BtnReset = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        TexNR = new javax.swing.JTextField();
        TexTR = new javax.swing.JTextField();
        RbtnNR = new javax.swing.JRadioButton();
        RbtnTR = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnAplicar.setForeground(new java.awt.Color(51, 51, 51));
        BtnAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        BtnAplicar.setText("Play");
        BtnAplicar.setToolTipText("Execute the Configuration");
        BtnAplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAplicar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAplicarMouseClicked(evt);
            }
        });
        BtnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAplicarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Attribute");

        CmbAtributos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CmbAtributos.setToolTipText("Select an attribute");

        BtnReset.setForeground(new java.awt.Color(51, 51, 51));
        BtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo.png"))); // NOI18N
        BtnReset.setText("Reset");
        BtnReset.setToolTipText("Reset the Parameters");
        BtnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnCerrar.setForeground(new java.awt.Color(51, 51, 51));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        BtnCerrar.setText("Close");
        BtnCerrar.setToolTipText("Close Configuration");
        BtnCerrar.setEnabled(false);
        BtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Discretize by :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        TexNR.setFont(new java.awt.Font("Tahoma", 0, 12));
        TexNR.setToolTipText("Number of Range");
        TexNR.setBounds(30, 60, 80, 30);
        jLayeredPane1.add(TexNR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TexTR.setFont(new java.awt.Font("Tahoma", 0, 12));
        TexTR.setToolTipText("Size of Range");
        TexTR.setEnabled(false);
        TexTR.setBounds(30, 160, 80, 30);
        jLayeredPane1.add(TexTR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(RbtnNR);
        RbtnNR.setSelected(true);
        RbtnNR.setText("Number of Range");
        RbtnNR.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        RbtnNR.setMargin(new java.awt.Insets(0, 0, 0, 0));
        RbtnNR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RbtnNRItemStateChanged(evt);
            }
        });
        RbtnNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnNRActionPerformed(evt);
            }
        });
        RbtnNR.setBounds(10, 30, 120, 15);
        jLayeredPane1.add(RbtnNR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(RbtnTR);
        RbtnTR.setText("Size of Range");
        RbtnTR.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        RbtnTR.setMargin(new java.awt.Insets(0, 0, 0, 0));
        RbtnTR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RbtnTRItemStateChanged(evt);
            }
        });
        RbtnTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnTRActionPerformed(evt);
            }
        });
        RbtnTR.setBounds(10, 120, 120, 15);
        jLayeredPane1.add(RbtnTR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CmbAtributos, 0, 202, Short.MAX_VALUE)
                        .addGap(99, 99, 99))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(BtnAplicar)
                        .addGap(29, 29, 29)
                        .addComponent(BtnCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnReset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAplicarMouseClicked
        
}//GEN-LAST:event_BtnAplicarMouseClicked

    private void BtnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAplicarActionPerformed
        String cad = "";
        char uc;
        int x=0;
        //------------------------
        colsel = datosEntrada.findColumn(CmbAtributos.getModel().getSelectedItem().toString());
        if(colsel == -1){
            TexNR.setText("");
            TexNR.setText("");
            JOptionPane.showMessageDialog(this, "you must select some attribute",
                    "Error in Configure Discretize",JOptionPane.ERROR_MESSAGE);
        } else {
            
            if(RbtnNR.isSelected()) {
                cad = TexNR.getText();
                bdrbtn = 0;
            } else if(RbtnTR.isSelected()) {
                cad = TexTR.getText();
                bdrbtn = 1;
            }
            x=0;
            
            for(int y = 0; y < cad.length(); y++) {
                uc = cad.charAt(y);
                if(uc>47 && uc<58) x++;
            }
            if(x==cad.length()) {
                val = Integer.parseInt(cad);
                BtnCerrar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "The value must be numerical",
                        "Error in Configure Rango Numerico",JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_BtnAplicarActionPerformed

    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
        
}//GEN-LAST:event_BtnResetMouseClicked

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        CmbAtributos.setSelectedIndex(0);
        TexNR.setText("");
        TexNR.setEnabled(true);
        TexTR.setText("");
        TexTR.setEnabled(false);
        RbtnNR.setSelected(true);
        RbtnTR.setSelected(false);
}//GEN-LAST:event_BtnResetActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        dispose();
        //System.exit( 0 );
}//GEN-LAST:event_BtnCerrarActionPerformed

    private void RbtnNRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RbtnNRItemStateChanged
        // TODO add your handling code here:
        TexNR.setEnabled(true);
        TexTR.setEnabled(false);
}//GEN-LAST:event_RbtnNRItemStateChanged

    private void RbtnTRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RbtnTRItemStateChanged
        // TODO add your handling code here:
        TexNR.setEnabled(false);
        TexTR.setEnabled(true);
}//GEN-LAST:event_RbtnTRItemStateChanged

    private void RbtnNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnNRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnNRActionPerformed

    private void RbtnTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnTRActionPerformed

    
    public int getColSelec () {
       return colsel; 
    }
    
    public int getValor () {
       return val; 
    }
      
    public int getSelRbtn () {
       return bdrbtn; 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new miAbrirDiscretizacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAplicar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnReset;
    private javax.swing.JComboBox CmbAtributos;
    private javax.swing.JRadioButton RbtnNR;
    private javax.swing.JRadioButton RbtnTR;
    private javax.swing.JTextField TexNR;
    private javax.swing.JTextField TexTR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
