/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * miconfigureParameters.java
 *
 * Created on 25-may-2012, 15:26:02
 */
package gui.Icons.Clasification;

import algorithm.classification.c45_1.TariyTableModel;
import algorithm.classification.c45_1.TreeCounter;
import gui.KnowledgeFlow.ChooserEscritorio;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Juan Carlos
 */
public class miconfigureParameters extends javax.swing.JFrame {

    private ClasificationIcon ci;
    public double minRows = 1.0;
    public double threshold = 1.0;
    public double training = 1.0;
    private TreeCounter c;
    private SpinnerNumberModel snmRows;
    private SpinnerNumberModel snmThreshold;
    private SpinnerNumberModel snmTraining;
    TariyTableModel dataOut1 = new TariyTableModel();
    TariyTableModel dataOut2 = new TariyTableModel();
    
    /** Creates new form configureParameters */
    public miconfigureParameters(ClasificationIcon ci) {
        initComponents();
        this.ci = ci;
        snmRows = new SpinnerNumberModel(ci.minRows, 0.0, 100.0, 0.25);
        snmThreshold= new SpinnerNumberModel(ci.threshold, 0.0, 100.0, 0.25);
        snmTraining = new SpinnerNumberModel(ci.trainingSet, 0.0, 100.0, 0.25);
        spnMinRows.setModel(snmRows);
        spnThreshold.setModel(snmThreshold);
        spnSizeSet.setModel(snmTraining);
    }
    
    public void updateIcon(ClasificationIcon icon){
        this.ci = icon;
        
        spnMinRows.setValue(ci.minRows);
        spnThreshold.setValue(ci.threshold);
        spnSizeSet.setValue(ci.trainingSet);
        
        minRows = (Double)spnMinRows.getValue();
        ci.minRows = minRows;
        threshold = (Double)spnThreshold.getValue();
        ci.threshold = threshold;
        // toca enviar los valore a ig
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spnMinRows = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnThreshold = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spnSizeSet = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pruning", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Min Rows by Node:");

        spnMinRows.setToolTipText("Minimum number of rows by node");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Threshold:");

        jLabel6.setText("%");

        spnThreshold.setToolTipText("Percentage of an attribute in the class");

        jLabel7.setText("%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spnThreshold, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnMinRows, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnMinRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Training Set", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Set Size :");

        spnSizeSet.setToolTipText("Size of Training set");

        jLabel4.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnSizeSet, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnSizeSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        jButton1.setText("Accept");
        jButton1.setToolTipText("Accept this parameters");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(7, 7, 7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float fsizeset = 0;
        int rows, cols, roundf = 0, cn = 0;
        float vlsp=0;
        
        minRows = (Double)spnMinRows.getValue();
        ci.minRows = minRows;
        threshold = (Double)spnThreshold.getValue();
        ci.threshold = threshold;
        
        rows = ci.dataIn.getRowCount();
        cols = ci.dataIn.getColumnCount();
        
        vlsp = Float.parseFloat(spnSizeSet.getValue().toString());
        ci.trainingSet = vlsp;
        
        Object[][] data1;
        
        Object[][] data2;
        
        String[] columnsName = new String[cols];
        
        if(vlsp == 100 || vlsp == 0){
            
            data1 = new Object[rows][cols];
            
            data2 = new Object[rows][cols];
            
            for(int i = 0; i < cols; i++){
                for(int j = 0; j < rows; j++){
                    
                    if(ci.dataIn.getValueAt(j ,i) == null){
                        JOptionPane.showMessageDialog(this, "The input data contain missing values. \n" +
                                "You would have to apply the filter \nRemove Missing or Remplace Missing",
                                "Error in Configure Parameters",JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    data1[j][i] = ci.dataIn.getValueAt(j ,i);
                    data2[j][i] = ci.dataIn.getValueAt(j ,i);
                }
                columnsName[i] = ci.dataIn.getColumnName(i);
            }
        } else{
            
            fsizeset = vlsp/100;
            fsizeset = fsizeset*rows;
            roundf = (int)fsizeset;
            
            data1 = new Object[roundf][cols];
            
            data2 = new Object[rows-roundf][cols];
            
            for(int i = 0; i < cols; i++){
                for(int j = 0; j < roundf; j++){
                    
                    if(ci.dataIn.getValueAt(j ,i) == null){
                        JOptionPane.showMessageDialog(this, "The input data contain missing values. \n" +
                                "You would have to apply the filter \nRemove Missing or Remplace Missing",
                                "Error in Configure Parameters",JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    data1[j][i] = ci.dataIn.getValueAt(j ,i);
                }
                cn = 0;
                for(int j = roundf; j < rows; j++){
                    
                    if(ci.dataIn.getValueAt(j ,i) == null){
                        JOptionPane.showMessageDialog(this, "The input data contain missing values. \n" +
                                "You would have to apply the filter \nRemove Missing or Remplace Missing",
                                "Error in Configure Parameters",JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    data2[cn][i] = ci.dataIn.getValueAt(j ,i);
                    cn ++;
                }
                columnsName[i] = ci.dataIn.getColumnName(i);
            }
        }
        
        dataOut1.setDatos(data1);
        dataOut2.setDatos(data2);
        dataOut1.setNomcol(columnsName);
        dataOut2.setNomcol(columnsName);
        
        ci.dataOut1 = dataOut1;
        ci.dataOut2 = dataOut2;
        
        //        System.out.println(spnMinRows.getValue().toString());
        //        TariyTableModel tariyData = new TariyTableModel();
        //        minRows = (int)(d*tariyData.getRowCount()/100);
        //        c = new TreeCounter(minRows, tariyData);
        //        c.start();
        ci.mnuRun.setEnabled(true);
        ChooserEscritorio.setStatus("Parameters loaded in " + ci.getName().trim());
        ci.setInfo("min Rows: " + minRows + "%" + "\nThreshold: " + threshold + "%" + "\n\nTraining Set: " + vlsp + "%");
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                configureParameters cp = new configureParameters(new ClasificationIcon(new JLabel(), 0 , 0, 0));
                cp.setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner spnMinRows;
    private javax.swing.JSpinner spnSizeSet;
    private javax.swing.JSpinner spnThreshold;
    // End of variables declaration//GEN-END:variables
}
