/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * miAbrirRemVal.java
 *
 * Created on 25-may-2012, 14:41:30
 */
package gui.Icons.Filters.ReplaceValue;

import gui.Icons.Filters.ValAtributos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Carlos
 */
public class miAbrirRemVal extends javax.swing.JFrame {

    AbstractTableModel datosEntrada;
    String[] atributos;
    ArrayList atris;
    String texval;
    ValAtributos valAtri;
    int colsel, nAtriSel;
    
    /** Creates new form miAbrirRemVal */
    public miAbrirRemVal(AbstractTableModel dataIn) {
        datosEntrada = dataIn;
        atributos  = new String[datosEntrada.getColumnCount()+1];
        atris = new ArrayList(1);
        int pa;
        //____________
        
        atributos[0] = "Select an Attribute";
        pa = 1;
        for(int i = 0; i < datosEntrada.getColumnCount(); i++) {
            if(datosEntrada.getColumnClass(i).getSimpleName().equals("String")) {
                atributos[pa] = datosEntrada.getColumnName(i);
                pa ++;
            }
        }
        initComponents();
    }
    
    public miAbrirRemVal() {
        atris = new ArrayList(1);
        initComponents();
    }
    
    public void setDatas(AbstractTableModel di, int indexColumn, ArrayList valuesAtribute, String replace) {
        datosEntrada = di;  
//        atris = new ArrayList(1);
        
        if(atributos == null){ // si apenas se instancia o si llega del guardado
            atributos = new String[datosEntrada.getColumnCount()+1];
            atributos[0] = "Select an Attribute";
            CmbItem.addItem(atributos[0]);
            for(int i = 1; i < datosEntrada.getColumnCount()+1; i++) {
                if(datosEntrada.getColumnClass(i-1).getSimpleName().equals("String")) {
                    atributos[i] = datosEntrada.getColumnName(i-1);
                    CmbItem.addItem(atributos[i]);
                }
            }  
        } 
        
        if(!replace.equals("")){// con esto miro que no sea la primera instancia, es decir despues del constructor inicial
            CmbItem.setSelectedIndex(indexColumn);

            valAtri = new ValAtributos(indexColumn, datosEntrada);
            if(valuesAtribute != null){ 
                for(int i = 0; i < valuesAtribute.size(); i++){
                    valAtri.setSelection(valuesAtribute.get(i));
                }
            }
            TableAtrib.setModel(valAtri);

            TexRemCon.setText(replace);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAplicar = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        CmbItem = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAtrib = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        TexRemCon = new javax.swing.JTextField();
        BtnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnAplicar.setForeground(new java.awt.Color(51, 51, 51));
        BtnAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        BtnAplicar.setText("Play");
        BtnAplicar.setToolTipText("Execute the Configuration");
        BtnAplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAplicar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAplicarActionPerformed(evt);
            }
        });

        BtnCerrar.setForeground(new java.awt.Color(51, 51, 51));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        BtnCerrar.setText("Close");
        BtnCerrar.setToolTipText("Close the Configuration");
        BtnCerrar.setEnabled(false);
        BtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        CmbItem.setFont(new java.awt.Font("Tahoma", 0, 16));
        CmbItem.setToolTipText("Select an Attribute");
        CmbItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbItemActionPerformed(evt);
            }
        });
        CmbItem.setBounds(20, 50, 210, 40);
        jLayeredPane2.add(CmbItem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Attribute");
        jLabel2.setBounds(20, 20, 60, 20);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alphabetics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jScrollPane1.setToolTipText("Alphabetical Values");

        TableAtrib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableAtrib);

        jScrollPane1.setBounds(10, 20, 200, 160);
        jLayeredPane5.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane5.setBounds(10, 110, 220, 210);
        jLayeredPane2.add(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Replace by :");
        jLabel3.setBounds(20, 330, 70, 20);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TexRemCon.setFont(new java.awt.Font("Tahoma", 0, 14));
        TexRemCon.setToolTipText("Value to Replace");
        TexRemCon.setBounds(20, 360, 210, 30);
        jLayeredPane2.add(TexRemCon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BtnReset.setForeground(new java.awt.Color(51, 51, 51));
        BtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo.png"))); // NOI18N
        BtnReset.setText("Reset");
        BtnReset.setToolTipText("Resete the Parameters");
        BtnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAplicar)
                    .addComponent(BtnReset, 0, 0, Short.MAX_VALUE)
                    .addComponent(BtnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnAplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(BtnCerrar)
                        .addGap(114, 114, 114)
                        .addComponent(BtnReset)
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAplicarActionPerformed
        String cad;
        char uc;
        int x = 0;
        //____________
        
//        cad = TexRemCon.getText();
//        for(int y = 0; y < cad.length(); y++) {
//            uc = cad.charAt(y);
//            if(uc>47 && uc<58) x++;
//        }
//        if(x==cad.length()) {
//            JOptionPane.showMessageDialog(this, "Replace by must contain alphabetical values ","Error in Configure Remplace Value.",JOptionPane.ERROR_MESSAGE);
//        } else 
            
        if(CmbItem.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "You must select some Attribute","Error in Configure Remplace Value",JOptionPane.ERROR_MESSAGE);  
        } else {
            texval = TexRemCon.getText();
            BtnCerrar.setEnabled(true);
            
            nAtriSel = 0;
            atris.clear();
            for(int f = 0; f < valAtri.getRowCount(); f++) {  // talves esta parte del for deberia ser en el boton aplicar anction performed
                if(valAtri.getValueAt(f,1).toString().equals("true")) {
                    atris.add(valAtri.getValueAt(f,0).toString());
                    nAtriSel ++;
                }
            }
        }    
}//GEN-LAST:event_BtnAplicarActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        //System.exit( 0 );
        dispose();
}//GEN-LAST:event_BtnCerrarActionPerformed

    private void CmbItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbItemActionPerformed
     
        colsel = datosEntrada.findColumn(CmbItem.getModel().getSelectedItem().toString());
        if(colsel == -1){
            TableAtrib.setModel(new DefaultTableModel());
        } else {
            valAtri = new ValAtributos(colsel, datosEntrada);
            TableAtrib.setModel(valAtri);
//            atris.clear();
        }
}//GEN-LAST:event_CmbItemActionPerformed

    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
        
}//GEN-LAST:event_BtnResetMouseClicked

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        CmbItem.setSelectedIndex(0);
        TexRemCon.setText("");
        TableAtrib.setModel(new DefaultTableModel());
}//GEN-LAST:event_BtnResetActionPerformed

    public ArrayList getAtriSel() {
        return atris;
    }
    
    public String getRemCon() {
        return texval;
    }
    
    public int getColSel() {
        return colsel;
    }
    
    public int getNumAtri() {
        return nAtriSel;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new miAbrirRemVal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAplicar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnReset;
    private javax.swing.JComboBox CmbItem;
    private javax.swing.JTable TableAtrib;
    private javax.swing.JTextField TexRemCon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
