/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Icons.Reduction.PAppletKmix;

import gui.Icons.Reduction.*;
import gui.Icons.Reduction.PAppletKmix.PAppletKmix2;
import gui.Icons.Reduction.PAppletKmix.PAppletKmix3;
import java.util.ArrayList;

/**
 *
 * @author JuanKDD
 */
public class configureMix extends javax.swing.JFrame {

    PAppletKmix2 mix2;
    PAppletKmix3 mix3;
    int cualPApplet = 2; // 2 para dos kernels, 3 para 3 kernels
    KmixIcon kmixicon;
    DDRmixIcon ddricon;
    int metMix = 0; // codigo del metodo si es 1 es KmixIcon si es 2 es DDRmixIcon

    /**
     * Creates new form configureDDR
     */
    public configureMix(KmixIcon icon) {
        initComponents();
        this.kmixicon = icon;
        metMix = 1;
    }
    
    public configureMix(DDRmixIcon icon) {
        initComponents();
        this.ddricon = icon;
        metMix = 2;
    }
    
    public void buildPapplet3K(ArrayList nameKernels){
        
        mix3 = new PAppletKmix3();
        pnlPApplet.add(mix3);
        mix3.init();
        
        String nk1 = nameKernels.get(0).toString();
        if(nk1.length()>12) nk1 = nk1.substring(0,12);
        
        String nk2 = nameKernels.get(1).toString();
        if(nk2.length()>12) nk2 = nk2.substring(0,12);

        String nk3 = nameKernels.get(2).toString();
        if(nk3.length()>12)nk3 = nk3.substring(0,12);

        mix3.setTitlesKernels("K1:"+nk1, "K2:"+nk2, "K3:"+nk3);
        
        cualPApplet = 3;
    }
    
    public void buildPapplet2K(ArrayList nameKernels){
        
        mix2 = new PAppletKmix2();
        pnlPApplet.add(mix2);
        mix2.init();
        
        String nk1 = nameKernels.get(0).toString();
        if(nk1.length()>20) nk1 = nk1.substring(0,20);
        
        String nk2 = nameKernels.get(1).toString();
        if(nk2.length()>20) nk2 = nk2.substring(0,20);

        mix2.setTitlesKernels("K1:"+nk1, "K2:"+nk2);
        
        cualPApplet = 2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPApplet = new javax.swing.JPanel();
        btnAccept = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        snpDim = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configure DDR");
        setResizable(false);

        pnlPApplet.setBorder(javax.swing.BorderFactory.createTitledBorder("Configure DDR"));

        javax.swing.GroupLayout pnlPAppletLayout = new javax.swing.GroupLayout(pnlPApplet);
        pnlPApplet.setLayout(pnlPAppletLayout);
        pnlPAppletLayout.setHorizontalGroup(
            pnlPAppletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        pnlPAppletLayout.setVerticalGroup(
            pnlPAppletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        btnAccept.setForeground(new java.awt.Color(51, 51, 51));
        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        btnAccept.setText("Play");
        btnAccept.setToolTipText("Accept this parameters");
        btnAccept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccept.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        btnexit.setText("Exit");
        btnexit.setEnabled(false);
        btnexit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnexit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Low Dimension");

        snpDim.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));
        snpDim.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPApplet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAccept)
                            .addComponent(snpDim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnexit))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPApplet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(snpDim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnAccept)
                        .addGap(58, 58, 58)
                        .addComponent(btnexit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        
        Integer dr = Integer.parseInt(snpDim.getValue().toString());
        
        if(metMix==1){
            
            kmixicon.d = dr;
        
            if(cualPApplet==2){
                kmixicon.R = mix2.R;
                kmixicon.B = mix2.B;
            }else if(cualPApplet==3){
                kmixicon.R = mix3.R;
                kmixicon.G = mix3.G;
                kmixicon.B = mix3.B;
            }
            kmixicon.getMnuRun().setEnabled(true);
            
        }else if(metMix==2){
            
            ddricon.d = dr;
        
            if(cualPApplet==2){
                ddricon.R = mix2.R;
                ddricon.B = mix2.B;
            }else if(cualPApplet==3){
                ddricon.R = mix3.R;
                ddricon.G = mix3.G;
                ddricon.B = mix3.B;
            }
            ddricon.getMnuRun().setEnabled(true);
        }
        
        
        btnexit.setEnabled(true);
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
          this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(configureMix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(configureMix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(configureMix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(configureMix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new configureMix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlPApplet;
    private javax.swing.JSpinner snpDim;
    // End of variables declaration//GEN-END:variables
}
