/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * miAbrirRemMissing.java
 *
 * Created on 25-may-2012, 14:33:43
 */
package gui.Icons.Filters.Proximity;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Juan Carlos
 */
public class miAbrirProximity extends javax.swing.JFrame {
    
    AbstractTableModel tipoVariables;
    String  proxType = "xatributos"; 
        
    int colObj = -1;
    int colsel[];
    int pc = 0;

    public miAbrirProximity(AbstractTableModel dataIn) {
        
        tipoVariables = new TipodVariablesSel(dataIn);
//        colsel = new int[tipoVariables.getRowCount()];
        initComponents();
        
        TableColumn column = null;
        column = TableTVariables.getColumnModel().getColumn(0);
        column.setPreferredWidth(150);
        column = TableTVariables.getColumnModel().getColumn(2);
        column.setPreferredWidth(50);
        column = TableTVariables.getColumnModel().getColumn(3);
        column.setPreferredWidth(30);
        
        TableColumn sportColumn = TableTVariables.getColumnModel().getColumn(3);
        JComboBox comboBox = new JComboBox();
        comboBox.addItem("Attribute");
        comboBox.addItem("Label");
        sportColumn.setCellEditor(new DefaultCellEditor(comboBox));
        initComponents();
    }

    /** Creates new form miAbrirRemMissing */
    public miAbrirProximity() {
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableTVariables = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        rbtnAttributes = new javax.swing.JRadioButton();
        rbtnRegisters = new javax.swing.JRadioButton();
        BtnAplicar = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setToolTipText("Select the Attributes and the Target");

        TableTVariables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TableTVariables);

        jTabbedPane1.addTab("Variables", jScrollPane3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Proximity matrix"));

        buttonGroup1.add(rbtnAttributes);
        rbtnAttributes.setSelected(true);
        rbtnAttributes.setText("By Attributes");

        buttonGroup1.add(rbtnRegisters);
        rbtnRegisters.setText("By registers");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnAttributes)
                    .addComponent(rbtnRegisters))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnAttributes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnRegisters)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnAplicar.setForeground(new java.awt.Color(51, 51, 51));
        BtnAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        BtnAplicar.setText("Play");
        BtnAplicar.setToolTipText("Execute the Configuration");
        BtnAplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAplicar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAplicarMouseClicked(evt);
            }
        });
        BtnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAplicarActionPerformed(evt);
            }
        });

        BtnCerrar.setForeground(new java.awt.Color(51, 51, 51));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        BtnCerrar.setText("Close");
        BtnCerrar.setToolTipText("Close the Configuration");
        BtnCerrar.setEnabled(false);
        BtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCerrar))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAplicarMouseClicked
         
}//GEN-LAST:event_BtnAplicarMouseClicked

    private void BtnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAplicarActionPerformed
         if(rbtnAttributes.isSelected()){
            proxType = "xatributos"; 
         }else if(rbtnRegisters.isSelected()){
            proxType = "xregistros"; 
         }
         
        for(int f = 0; f < tipoVariables.getRowCount(); f++ ){
            if(tipoVariables.getValueAt(f,2).toString().equals("Label")) {
                colObj = f; // colsel de los atributos seleccionados
            }
        }
         
         pc = 0; // Con pc se sabe cuantas columnas quedan habilitadas
         for(int f = 0; f < tipoVariables.getRowCount(); f++ ){
            if(!tipoVariables.getValueAt(f,1).toString().equals("String") && f != colObj) {
                colsel[pc] = f; // colsel son los atributos seleccionados
                pc++;
            }
        }

         BtnCerrar.setEnabled(true);
}//GEN-LAST:event_BtnAplicarActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        //System.exit( 0 );
        this.dispose();
}//GEN-LAST:event_BtnCerrarActionPerformed

    public String getProxType(){
        return this.proxType;
    }
    
    public int[] getcolsSel(){
        return this.colsel;
    }
    
    public int getColObj(){
        return this.colObj;
    }
    
    public int getNumColsSel(){
        return this.pc;
    }
    
    public void setDatas(AbstractTableModel dataIn) {
        tipoVariables = new TipodVariablesSel(dataIn);


        TableTVariables.setModel(tipoVariables);
        TableTVariables.setDefaultRenderer(Object.class, new RenderCelda()); // pone la celda en rojo si es string ya que no se puede computar

        colsel = new int[tipoVariables.getRowCount()];
        
        TableColumn column = null;
        column = TableTVariables.getColumnModel().getColumn(0);
        column.setPreferredWidth(150);
        column = TableTVariables.getColumnModel().getColumn(2);
        column.setPreferredWidth(30);
        
        TableColumn sportColumn = TableTVariables.getColumnModel().getColumn(2);
        JComboBox comboBox = new JComboBox();
        comboBox.addItem("Attribute");
        comboBox.addItem("Label");
        sportColumn.setCellEditor(new DefaultCellEditor(comboBox)); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new miAbrirProximity().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAplicar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JTable TableTVariables;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbtnAttributes;
    private javax.swing.JRadioButton rbtnRegisters;
    // End of variables declaration//GEN-END:variables
}
